import { ListCartItem } from '@/models';

export const DataCarts: ListCartItem[] = [
  {
    id: 1,
    isChoose: false,
    image: '../../../images/bottleWines/wine1.png',
    product: 'Rioja Gran Reserva 2016',
    price: '20',
  },
  {
    id: 2,
    isChoose: false,
    image: '../../../images/image_1.jpg',
    product: 'Bottega Diamond',
    price: '20',
  },
  {
    id: 3,
    isChoose: false,
    image: '../../../images/image_2.jpg',
    product: 'Bottega Gold Prosecco',
    price: '20',
  },
  {
    id: 4,
    isChoose: false,
    image: '../../../images/image_3.jpg',
    product: 'Bottega Rose Gold',
    price: '20',
  },
  {
    id: 5,
    isChoose: false,
    image: '../../../images/image_4.jpg',
    product: 'Freixenet Italian Rosé',
    price: '20',
  },
  {
    id: 6,
    isChoose: false,
    image: '../../../images/image_5.jpg',
    product: 'Tener Brut Castello Banfi',
    price: '20',
  },
  {
    id: 7,
    isChoose: false,
    image: '../../../images/image_6.jpg',
    product: 'Bottega Stardust Prosecco',
    price: '20',
  },
  {
    id: 8,
    isChoose: false,
    image: '../../../images/image_7.jpg',
    product: 'Essenza Primitivo di Manduria DOP 75 CL',
    price: '20',
  },
  {
    id: 9,
    isChoose: false,
    image: '../../../images/image_8.jpg',
    product: 'Wine Varvaglione Malvasia Del Salento 12 E Mezzo',
    price: '20',
  },
  {
    id: 10,
    isChoose: false,
    image: '../../../images/image_9.jpg',
    product: '12 E Mezzo Primitivo Del Salento',
    price: '20',
  },
  {
    id: 11,
    isChoose: false,
    image: '../../../images/image_65.jpg',
    product: `'Ca' Botta Vini'`,
    price: '20',
  },
  {
    id: 12,
    isChoose: false,
    image: '../../../images/image_89.jpg',
    product: 'Carpineto Dogajolo Toscano Bianco IGT',
    price: '20',
  },
  {
    id: 13,
    isChoose: false,
    image: '../../../images/image_81.jpg',
    product: 'DE FALCO Rosato Salento IGT',
    price: '20',
  },
  {
    id: 14,
    isChoose: false,
    image: '../../../images/image_319.jpg',
    product: 'Vino 7 Colores Reserva Cepas Carmenere',
    price: '20',
  },
];
